# 靜態政策資料：將已整理好的台北市青年補助/服務資料直接輸出供寫入 ChromaDB
import logging

logger = logging.getLogger(__name__)

POLICIES = [
    {
        "id": "PO004",
        "title": "臺北市青年實習津貼",
        "status": "受理中",
        "categories": ["就業", "實習"],
        "age": "15–35歲",
        "residence": "設籍台北市6個月以上",
        "identity": "在學（高中職/大專/研究所）",
        "amounts": [
            "60日：$10,000｜低收：$20,000",
            "90日：$15,000｜低收：$30,000",
            "交通60日：$2,400 / 90日：$3,600",
            "健康檢查：最高 $1,000",
        ],
        "deadline": "達標後30日內，最晚11/30",
        "rules": [
            "每人每年限申請一次",
            "不可與他政府相同性質津貼重複",
            "需提交250字以上實習心得",
            "預算用罄即停止",
        ],
        "url": "https://service.taipei/case-detail/PO004",
        "contact": "臺北青年職涯發展中心 02-23958567｜仁愛路一段17號2樓",
    },
    {
        "id": "PO004B",
        "title": "青年創新職場實習補助（企業端）",
        "status": "受理中",
        "categories": ["就業", "實習", "企業"],
        "age": "不限（企業申請）",
        "residence": "台北市設立未滿8年之公司/NPO",
        "identity": "新創企業、非營利組織",
        "amounts": [
            "每月每位青年補助 $10,000（最長6個月）",
            "單一單位年度上限 $150,000",
        ],
        "deadline": "每年最後申請日11月10日",
        "rules": [
            "每月實習時數須達64小時以上",
            "需依基本工資給薪並投保勞保",
            "實習青年不可為負責人二親等內",
        ],
        "url": "https://youth.gov.taipei/announcement/latest-announcement/e9f60caf-7421-4ce9-aca9-367594a78546",
        "contact": "青年局 02-2351-4078",
    },
    {
        "id": "NEW01",
        "title": "青年職涯進修補助計畫",
        "status": "受理中",
        "categories": ["就業", "進修"],
        "age": "18–29歲（未滿30歲）",
        "residence": "設籍台北市6個月以上",
        "identity": "個人（非在學限制）",
        "amounts": [
            "最高補助 $10,000（單一課程學費）",
            "低收入戶/中低收入戶：最高 $20,000",
        ],
        "deadline": "每年11/30（或經費用罄）；每2年申請1次",
        "rules": [
            "課程開訓前21個工作日提出申請",
            "申請前3個月內須先接受TYS職涯諮詢",
            "補習班/學校/職訓機構/線上平台課程皆可",
            "不可與他機關相同補助重複",
        ],
        "url": "https://tpyd.104.com.tw/studies",
        "contact": "臺北青年職涯發展中心 02-23958567｜仁愛路一段17號2樓（週二至週日 09:00–18:00）",
    },
    {
        "id": "PO009",
        "title": "臺北市青年創業融資貸款",
        "status": "受理中",
        "categories": ["創業"],
        "age": "成年–45歲，設籍台北市1年以上",
        "residence": "公司登記地址在台北市，未滿5年",
        "identity": "公司/商業/有限合夥負責人",
        "amounts": [
            "簡易貸（≦$120萬）：免審查小組",
            "一般貸：最高 $200萬",
            "特殊條件：最高 $400萬",
            "創業準備金：成立未滿1年可加借 $100萬",
            "利率：郵儲2年定存利率+0.555%，利息全額補貼",
        ],
        "deadline": "全年受理，審查小組每月一次",
        "rules": [
            "3年內需完成20小時政府創業輔導課程",
            "以貸一次為限（攤還1年後可再貸）",
            "信用保證成數9成5（免擔保）",
        ],
        "url": "https://service.taipei/case-detail/PO009",
        "contact": "青年局創業諮詢 02-2395-8567#66 / 02-2351-4078#1325｜仁愛路一段17號2樓",
    },
    {
        "id": "PO006",
        "title": "青年創業共享空間租賃補助",
        "status": "暫停受理",
        "categories": ["創業"],
        "age": "18–45歲",
        "residence": "不限",
        "identity": "需有公司設立證明",
        "amounts": ["補助共享空間租賃費（依要點核定）"],
        "deadline": "暫停受理中",
        "rules": ["需檢附租賃契約書", "需公司設立登記證明"],
        "url": "https://service.taipei/case-detail/PO006",
        "contact": "青年局 02-2351-4078",
    },
    {
        "id": "PO007",
        "title": "職涯培力及創業活動補助",
        "status": "暫停受理",
        "categories": ["創業", "就業"],
        "age": "不限（機構申請）",
        "residence": "不限",
        "identity": "法人/機構/學校",
        "amounts": ["補助辦理職涯或創業活動費用"],
        "deadline": "分三期：1/5/9月各15天，目前暫停",
        "rules": [
            "活動結束後20日內核銷",
            "變更活動內容須提前7日報備",
            "核准後項目金額不得互相勻用",
        ],
        "url": "https://service.taipei/case-detail/PO007",
        "contact": "青年局",
    },
    {
        "id": "PO002",
        "title": "臺北市青年留學生就學貸款補助",
        "status": "受理中",
        "categories": ["國際", "補助"],
        "age": "20–44歲（最新辦法45歲以下）",
        "residence": "設籍台北市1年以上",
        "identity": "赴海外就讀碩博士或專技證照",
        "amounts": [
            "碩士/專技證照：最高 $100萬",
            "博士：最高 $200萬",
            "貸款前10年利息全額補助（台北富邦銀行承辦）",
        ],
        "deadline": "臨櫃辦理，全年受理",
        "rules": [
            "所得淨額未達課稅級距30%或未達申報標準",
            "就讀學校需在政府認可名冊",
            "非英文文件需政府立案翻譯社中文譯本",
        ],
        "url": "https://service.taipei/case-detail/PO002",
        "contact": "台北富邦銀行全台分行辦理",
    },
    {
        "id": "PO008",
        "title": "促進青年國際發展補助",
        "status": "受理中",
        "categories": ["國際"],
        "age": "15–45歲（個人）",
        "residence": "設籍/就學/就業於台北市",
        "identity": "個人、學校、立案團體",
        "amounts": [
            "個人每案最高 $20,000，每年最多2案合計不超過 $25,000",
            "學校/公益弱勢族群：最高每案 $200,000",
        ],
        "deadline": "活動前20個工作天提出，年度至11/30",
        "rules": [
            "需三個以上國家參與之國際活動",
            "含國際展演、競技、大型會議（不含純學術或一般交流）",
            "活動後需提交成果報告書及10張以上照片",
        ],
        "url": "https://service.taipei/case-detail/PO008",
        "contact": "青年局 02-2351-4078",
    },
    {
        "id": "NEW02",
        "title": "海外實習計畫",
        "status": "受理中",
        "categories": ["國際", "就業"],
        "age": "18–45歲",
        "residence": "設籍/就學/就業於台北市",
        "identity": "需英文中高級以上語言證明",
        "amounts": ["補助內容待確認（含部分費用補助）"],
        "deadline": "每年第1季招募，暑假期間出隊",
        "rules": [
            "與美、亞洲10+家國際機構合作",
            "英文中高級以上語言證明必備",
        ],
        "url": "https://youth.gov.taipei",
        "contact": "青年局 02-2351-4078",
    },
    {
        "id": "PO005",
        "title": "協助青年多元發展補助",
        "status": "受理中",
        "categories": ["補助"],
        "age": "不限（團體申請）",
        "residence": "不限",
        "identity": "立案團體/學生社團/機構",
        "amounts": ["每場次最高 $20,000"],
        "deadline": "活動前20日提出",
        "rules": [
            "需立案證書及組織章程",
            "需公職人員利益衝突迴避法自主檢核表",
        ],
        "url": "https://service.taipei/case-detail/PO005",
        "contact": "青年局",
    },
    {
        "id": "EA026",
        "title": "青年就業領航計畫穩定就業津貼",
        "status": "暫停受理",
        "categories": ["就業"],
        "age": "不限（需參加勞動部計畫）",
        "residence": "不限",
        "identity": "參加勞動部青年就業領航計畫者",
        "amounts": ["連續受僱30日後90日內可申請"],
        "deadline": "暫停受理",
        "rules": ["需由勞動部分署名單核定", "每年1/4/7/10月撥款"],
        "url": "https://service.taipei/case-detail/EA026",
        "contact": "就服處",
    },
    {
        "id": "AN013",
        "title": "社會住宅育兒租金加碼補貼",
        "status": "受理中",
        "categories": ["住宅", "育兒"],
        "age": "不限（需育有12歲以下子女）",
        "residence": "台北市社會住宅有效租期承租人",
        "identity": "社宅承租人",
        "amounts": ["租金加碼補貼（依各社宅公告）"],
        "deadline": "每月15日前提出，次月起生效",
        "rules": ["郵戳為憑，需補件以補件合格日計"],
        "url": "https://service.taipei/case-detail/AN013",
        "contact": "臺北市住宅及都市更新中心 02-25955116",
    },
    {
        "id": "PO001",
        "title": "臺北市政府青年局場地租借",
        "status": "受理中",
        "categories": ["場地"],
        "age": "不限",
        "residence": "不限",
        "identity": "不限",
        "amounts": ["依場地收費基準表（需繳保證金）"],
        "deadline": "使用日前90日內申請",
        "rules": ["核准後5日內繳清，逾期視為放棄"],
        "url": "https://service.taipei/case-detail/PO001",
        "contact": "青年局 02-2351-4078",
    },
]


def crawl() -> list[dict]:
    """將靜態政策資料轉為標準格式。"""
    results = []
    for p in POLICIES:
        content_parts = [
            f"【{p['title']}】",
            f"狀態：{p['status']}",
            f"適用年齡：{p['age']}",
            f"戶籍條件：{p['residence']}",
            f"申請身份：{p['identity']}",
            f"補助金額：{'；'.join(p['amounts'])}",
            f"申請期限：{p['deadline']}",
            f"注意事項：{'；'.join(p['rules'])}",
            f"類別：{'、'.join(p['categories'])}",
            f"聯絡方式：{p['contact']}",
        ]
        results.append({
            "title": p["title"],
            "content": "\n".join(content_parts),
            "url": p["url"],
            "source": "taipei_youth_policy",
        })

    logger.info("靜態政策資料載入完成，共 %d 筆", len(results))
    return results
